apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      name: cassandra-pod
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra

---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-srv
spec:
  selector:
    app: cassandra
  ports:
    - name: db
      protocol: TCP
      port: 9042
      targetPort: 9042
