apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - port: 80
      targetPort: 5173
      nodePort: 30001 # Specify NodePort if type is NodePort
