apiVersion: v1
kind: Service
metadata:
  name: django-server-srv
spec:
  type: NodePort
  selector:
    app: django-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8000
      nodePort: 30003
