apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-server
  template:
    metadata:
      name: node-server-pod
      labels:
        app: node-server
    spec:
      containers:
        - name: node-server
          image: yegeta100/node-service:v1

---
apiVersion: v1
kind: Service
metadata:
  name: node-server-srv
spec:
  type: NodePort
  selector:
    app: node-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002

---
apiVersion: v1
kind: Service
metadata:
  name: node-server-cluster-srv
spec:
  type: ClusterIP # Internal access only
  selector:
    app: node-server
  ports:
    - protocol: TCP
      port: 3000 # Internal cluster port
      targetPort: 3000 # Port that the node-server container listens on
