apiVersion: v1
kind: Service
metadata:
  name: node-server-srv
spec:
  type: NodePort
  selector:
    app: node-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002
