apiVersion: v1
kind: Service
metadata:
  name: node-server-cluster-srv
spec:
  type: ClusterIP # Internal access only
  selector:
    app: node-server
  ports:
    - protocol: TCP
      port: 3000 # Internal cluster port
      targetPort: 3000 # Port that the node-server container listens on
